name: Generate Snake

on:
  schedule: # roda a cada 12 horas
    - cron: "0 */12 * * *"
  workflow_dispatch: # permite rodar manualmente

jobs:
  build:
    name: Generate snake animation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate Snake SVG
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: beeinblue
          outputs: dist/github-contribution-grid-snake.svg

      - name: Push Snake to output branch
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
